### ISSUE TITLE
Question about XML schemas

### ISSUE THREAD

**Issue by simplepersonru** [cim-iec/libcimpp#23]
Hello!

If you look at the CMS project files and compare them with the public CGMES schema, it's easy to see the connections. CGMES in the public domain is easy to find, and it is also in your repositories

Please tell me where you can find the sources of the RDF schema, from which, for example, the namespace IEC61970_17v07 turned out. Or did you write these classes yourself based on the standard documents? Or did you purchase them from some official sources? I would be very grateful for an answer

for example,  `IdentifiedObject `from IEC61970_17v07 has `aliasName` property, and CGMES `IdentifiedObject` has not

https://github.com/sogno-platform/libcimpp/blob/master/IEC61970_17v07/IEC61970/Base/Core/IdentifiedObject.h
https://github.com/sogno-platform/libcimpp/blob/master/CGMES_2.4.15_27JAN2020/IdentifiedObject.hpp

**Comment by m-mirz** [comment]
I don't think that the IEC61970 classes are relevant anymore. The focus is on CGMES. Back then, we have generated these classes ourselves.
