### ISSUE TITLE
Relicense libcimpp

### ISSUE THREAD

**Issue by m-mirz** [cim-iec/libcimpp#25]
It would be great to align the libcimpp license with cimgen. The Apache 2 license facilitates commercial use of the library and contributions.

Please let me know if you approve this motion to relicense libcimpp under Apache 2.

- [x] @achim-voelker
- [x] @MaxKissgen 
- [x] @dknibbe 
- [x] @stv0g 
- [x] @richardmarston 
- [x] @guelfey 
- [x] @lukasrazik 
- [x] @pdressen 
- [ ] @mohkoh19 
- [ ] @SimonGrimmACS 
- [ ] @taojunli

**Comment by stv0g** [comment]
I support a relicensing to Apache-2.0

**Comment by guelfey** [comment]
Sure, I agree to relicense my contributions under Apache-2.0.

**Comment by richardmarston** [comment]
I agree to relicense my contributions under Apache-2.0.

**Comment by MaxKissgen** [comment]
I also support the motion to relicense libcimpp under Apache 2.

**Comment by dknibbe** [comment]
I support relicensing libcimpp under Apache 2.

**Comment by achim-voelker** [comment]
I support relicensing libcimpp under Apache 2.

**Comment by lukasrazik** [comment]
I support a relicensing to Apache-2.0

**Comment by pdressen** [comment]
I support relicensing libcimpp under Apache 2.

**Comment by m-mirz** [comment]
Thanks everyone! Looking at the contributions, we cover the relevant parts of the project :-)
